export const ADD_STAR = 'ADD_STAR'
export const RUDCE_STAR = 'RUDCE_STAR'
export const ORDER_REQ = 'ORDER_REQ'
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_FAILURE = 'ORDER_FAILURE'
